name: Démarrage automatique

# Controls when the workflow will run
on:
# démarrage à 8:00
  schedule:
    # Tous les matins du lundi au vendredi à 8:00
    - cron: '0 8 * * 1-5'

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkoutmaster

    - name: "Terraform Format"
      uses: hashicorp/terraform-github-actionsmaster

      with:

        tf_actions_version: 0.12.13
        tf_actions_subcommand : "fnt"

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actionsmaster

      with:

        tf_actions_version: 0.12.13
        tf_actions_subcommand : "init"

    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actionsmaster

      with:

        tf_actions_version: 0.12.13
        tf_actions_subcommand : "plan"

    - name: "Terraform Apply"
      uses: hashicorp/terraform-github-actionsmaster

      with:

        tf_actions_version: 0.12.13
        tf_actions_subcommand : "apply"
